version: "3"
networks:
  helix_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/24

services:

  node_0:
    build:
      context: ./helix-1.0
      dockerfile: Dockerfile0
    hostname: node_0
    restart: unless-stopped
    volumes:
      - ./helix-1.0/target:/target
      - ./helix-1.0/configs:/configs
      - ./logs:/logs
      - ./dbs/node_0_db:/db
      - ./dbs/node_0_log:/mainnet.log
      - ./spent_addresses/node_0_db:/spent-addresses-db
      - ./spent_addresses/node_0_log:/spent-addresses-log
      - ./snapshots/node_0_snapshots:/snapshots
    environment:
      - JAVA_MAX_MEMORY=4096m
      - JAVA_MIN_MEMORY=256m
    ports:
      - "8085:8085"
      - "4100:4100/udp"
    networks:
      helix_network:
        ipv4_address: 172.20.0.2

  node_1:
    build:
      context: ./helix-1.0
      dockerfile: Dockerfile1
    hostname: node_1
    restart: unless-stopped
    volumes:
      - ./helix-1.0/target:/target
      - ./helix-1.0/configs:/configs
      - ./logs:/logs
      - ./dbs/node_1_db:/db
      - ./dbs/node_1_log:/mainnet.log
      - ./spent_addresses/node_1_db:/spent-addresses-db
      - ./spent_addresses/node_1_log:/spent-addresses-log
      - ./snapshots/node_1_snapshots:/snapshots
    environment:
      - JAVA_MAX_MEMORY=4096m
      - JAVA_MIN_MEMORY=256m
    ports:
      - "8086:8086"
      - "4101:4101/udp"
    networks:
      helix_network:
        ipv4_address: 172.20.0.3

  node_2:
    build:
      context: ./helix-1.0
      dockerfile: Dockerfile2
    hostname: node_2
    restart: unless-stopped
    volumes:
      - ./helix-1.0/target:/target
      - ./helix-1.0/configs:/configs
      - ./logs:/logs
      - ./dbs/node_2_db:/db
      - ./dbs/node_2_log:/mainnet.log
      - ./spent_addresses/node_2_db:/spent-addresses-db
      - ./spent_addresses/node_2_log:/spent-addresses-log
      - ./snapshots/node_2_snapshots:/snapshots
    environment:
      - JAVA_MAX_MEMORY=4096m
      - JAVA_MIN_MEMORY=256m
    ports:
      - "8087:8087"
      - "4102:4102/udp"
    networks:
      helix_network:
        ipv4_address: 172.20.0.4

  node_3:
    build:
      context: ./helix-1.0
      dockerfile: Dockerfile3
    hostname: node_3
    restart: unless-stopped
    volumes:
      - ./helix-1.0/target:/target
      - ./helix-1.0/configs:/configs
      - ./logs:/logs
      - ./dbs/node_3_db:/db
      - ./dbs/node_3_log:/mainnet.log
      - ./spent_addresses/node_3_db:/spent-addresses-db
      - ./spent_addresses/node_3_log:/spent-addresses-log
      - ./snapshots/node_3_snapshots:/snapshots
    environment:
      - JAVA_MAX_MEMORY=4096m
      - JAVA_MIN_MEMORY=256m
    ports:
      - "8088:8088"
      - "4103:4103/udp"
    networks:
      helix_network:
        ipv4_address: 172.20.0.5

  node_4:
    build:
      context: ./helix-1.0
      dockerfile: Dockerfile4
    hostname: node_4
    restart: unless-stopped
    volumes:
      - ./helix-1.0/target:/target
      - ./helix-1.0/configs:/configs
      - ./logs:/logs
      - ./dbs/node_4_db:/db
      - ./dbs/node_4_log:/mainnet.log
      - ./spent_addresses/node_4_db:/spent-addresses-db
      - ./spent_addresses/node_4_log:/spent-addresses-log
      - ./snapshots/node_4_snapshots:/snapshots
    environment:
      - JAVA_MAX_MEMORY=4096m
      - JAVA_MIN_MEMORY=256m
    ports:
      - "8089:8089"
      - "4104:4104/udp"
    networks:
      helix_network:
        ipv4_address: 172.20.0.6

  node_5:
    build:
      context: ./helix-1.0
      dockerfile: Dockerfile5
    hostname: node_5
    restart: unless-stopped
    volumes:
      - ./helix-1.0/target:/target
      - ./helix-1.0/configs:/configs
      - ./logs:/logs
      - ./dbs/node_5_db:/db
      - ./dbs/node_5_log:/mainnet.log
      - ./spent_addresses/node_5_db:/spent-addresses-db
      - ./spent_addresses/node_5_log:/spent-addresses-log
      - ./snapshots/node_5_snapshots:/snapshots
    environment:
      - JAVA_MAX_MEMORY=4096m
      - JAVA_MIN_MEMORY=256m
    ports:
      - "8090:8090"
      - "4105:4105/udp"
    networks:
      helix_network:
        ipv4_address: 172.20.0.7

  node_6:
    build:
      context: ./helix-1.0
      dockerfile: Dockerfile6
    hostname: node_6
    restart: unless-stopped
    volumes:
      - ./helix-1.0/target:/target
      - ./helix-1.0/configs:/configs
      - ./logs:/logs
      - ./dbs/node_6_db:/db
      - ./dbs/node_6_log:/mainnet.log
      - ./spent_addresses/node_6_db:/spent-addresses-db
      - ./spent_addresses/node_6_log:/spent-addresses-log
      - ./snapshots/node_6_snapshots:/snapshots
    environment:
      - JAVA_MAX_MEMORY=4096m
      - JAVA_MIN_MEMORY=256m
    ports:
      - "8091:8091"
      - "4106:4106/udp"
    networks:
      helix_network:
        ipv4_address: 172.20.0.8

  node_7:
    build:
      context: ./helix-1.0
      dockerfile: Dockerfile7
    hostname: node_7
    restart: unless-stopped
    volumes:
      - ./helix-1.0/target:/target
      - ./helix-1.0/configs:/configs
      - ./logs:/logs
      - ./dbs/node_7_db:/db
      - ./dbs/node_7_log:/mainnet.log
      - ./spent_addresses/node_7_db:/spent-addresses-db
      - ./spent_addresses/node_7_log:/spent-addresses-log
      - ./snapshots/node_7_snapshots:/snapshots
    environment:
      - JAVA_MAX_MEMORY=4096m
      - JAVA_MIN_MEMORY=256m
    ports:
      - "8092:8092"
      - "4107:4107/udp"
    networks:
      helix_network:
        ipv4_address: 172.20.0.9

  nginx:
    restart: unless-stopped
    build: ./nginx/
    ports:
      - "80:80"
      - "81:81"
    networks:
      helix_network:
        ipv4_address: 172.20.0.10

  prometheus:
    restart: unless-stopped
    build: ./prometheus/
    ports:
      - "9090:9090"
    networks:
      helix_network:
        ipv4_address: 172.20.0.11

  grafana:
    restart: unless-stopped
    build: ./grafana/
    ports:
      - "3000:3000"
    networks:
      helix_network:
        ipv4_address: 172.20.0.12

  mtail:
    build:
      context: ./mtail
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "3903:3903"
    volumes:
      - ./logs:/logs
    networks:
      helix_network:
        ipv4_address: 172.20.0.13
    command: ["-progs", "./helix_log_analysis.mtail", "-logs", "/logs/*.log"]
