version: "3"
networks:
  helix_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/24

services:

  node_0:
    build:
      context: ./helix-1.0
      dockerfile: Dockerfile0
    hostname: node_0
    restart: unless-stopped
    volumes:
      - ./helix-1.0/src:/src
      - ./helix-1.0/target:/target
      - ./helix-1.0/configs:/configs
      - ./logs:/logs
      - ./dbs/node_0_db:/mainnet-db
      - ./dbs/node_0_log:/mainnet-db-log
      - ./spent_addresses/node_0_db:/mainnet-spent-addresses-db
      - ./spent_addresses/node_0_log:/mainnet-spent-addresses-log
      - ./snapshots/node_0_snapshots:/mainnet-snapshot
    environment:
      - JAVA_MAX_MEMORY=4096m
      - JAVA_MIN_MEMORY=256m
    ports:
      - "8085:8085"
      - "4100:4100/udp"
    networks:
      helix_network:
        ipv4_address: 172.20.0.2

  node_1:
    build:
      context: ./helix-1.0
      dockerfile: Dockerfile1
    hostname: node_1
    restart: unless-stopped
    volumes:
      - ./helix-1.0/src:/src
      - ./helix-1.0/target:/target
      - ./helix-1.0/configs:/configs
      - ./logs:/logs
      - ./dbs/node_1_db:/mainnet-db
      - ./dbs/node_1_log:/mainnet-db-log
      - ./spent_addresses/node_1_db:/mainnet-spent-addresses-db
      - ./spent_addresses/node_1_log:/mainnet-spent-addresses-log
      - ./snapshots/node_1_snapshots:/mainnet-snapshot
    environment:
      - JAVA_MAX_MEMORY=4096m
      - JAVA_MIN_MEMORY=256m
    ports:
      - "8086:8086"
      - "4101:4101/udp"
    networks:
      helix_network:
        ipv4_address: 172.20.0.3

  node_2:
    build:
      context: ./helix-1.0
      dockerfile: Dockerfile2
    hostname: node_2
    restart: unless-stopped
    volumes:
      - ./helix-1.0/src:/src
      - ./helix-1.0/target:/target
      - ./helix-1.0/configs:/configs
      - ./logs:/logs
      - ./dbs/node_2_db:/mainnet-db
      - ./dbs/node_2_log:/mainnet-db-log
      - ./spent_addresses/node_2_db:/mainnet-spent-addresses-db
      - ./spent_addresses/node_2_log:/mainnet-spent-addresses-log
      - ./snapshots/node_2_snapshots:/mainnet-snapshot
    environment:
      - JAVA_MAX_MEMORY=4096m
      - JAVA_MIN_MEMORY=256m
    ports:
      - "8087:8087"
      - "4102:4102/udp"
    networks:
      helix_network:
        ipv4_address: 172.20.0.4

  node_3:
    build:
      context: ./helix-1.0
      dockerfile: Dockerfile3
    hostname: node_3
    restart: unless-stopped
    volumes:
      - ./helix-1.0/src:/src
      - ./helix-1.0/target:/target
      - ./helix-1.0/configs:/configs
      - ./logs:/logs
      - ./dbs/node_3_db:/mainnet-db
      - ./dbs/node_3_log:/mainnet-db-log
      - ./spent_addresses/node_3_db:/mainnet-spent-addresses-db
      - ./spent_addresses/node_3_log:/mainnet-spent-addresses-log
      - ./snapshots/node_3_snapshots:/mainnet-snapshot
    environment:
      - JAVA_MAX_MEMORY=4096m
      - JAVA_MIN_MEMORY=256m
    ports:
      - "8088:8088"
      - "4103:4103/udp"
    networks:
      helix_network:
        ipv4_address: 172.20.0.5

  nginx:
    restart: unless-stopped
    build: ./nginx/
    ports:
      - "7423:7423"
      - "8423:8423"
    networks:
      helix_network:
        ipv4_address: 172.20.0.6

  prometheus:
    restart: unless-stopped
    build: ./prometheus/
    ports:
      - "9090:9090"
    networks:
      helix_network:
        ipv4_address: 172.20.0.7

  grafana:
    restart: unless-stopped
    build: ./grafana/
    ports:
      - "3000:3000"
    networks:
      helix_network:
        ipv4_address: 172.20.0.8

  mtail:
    build:
      context: ./mtail
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "3903:3903"
    volumes:
      - ./logs:/logs
    networks:
      helix_network:
        ipv4_address: 172.20.0.9
    command: ["-progs", "./helix_log_analysis.mtail", "-logs", "/logs/tangle*.log"]
