
global:
  scrape_interval: 5s
  evaluation_interval: 10s

scrape_configs:
  - job_name: 'helix_logs'
    scrape_interval: 5s
    static_configs:
      - targets: ['172.20.0.13:3903']
        labels:
          group: 'logs'
