{
 "title": "Basic docker cluster",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "TPM (totalTransaction) from Node",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(total_transactions{job=\"node_log_file\"}[1m])"
    }
   ]
  },
  {
   "title": "Total transactions from Node",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "total_transactions" }
   ]
  },
  {
   "title": "Total stored transactions from API",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 5, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "stored_tx" }
   ]
  },
  {
   "title": "Transactions per minute per node from API",
   "type": "graph",
   "description": "Transaction rate over the last minute",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(stored_tx{job=\"node_prom_client\"}[1m])"
    }
   ]
  },
  {
   "title": "Total transactions per minute from API",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short", "label": "TPM" }
   ],
   "targets": [
    {
     "expr": "sum by (job)(rate(stored_tx{job=\"node_prom_client\"}[1m])) "
    }
   ]
  }
 ]
}