{
 "title": "dev-ops",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Stored tx",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "stored" }
   ]
  },
  {
   "title": "Stored Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (filename)(rate(stored{job=\"helix_logs\"}[5m]))  "
    }
   ]
  },
  {
   "title": "Received Rate ",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (filename)(rate(rcv{job=\"helix_logs\"}[5m]))  "
    }
   ]
  },
  {
   "title": "Received",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "targets": [
    { "expr": "rcv" }
   ]
  },
  {
   "title": "Reply Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (filename)(rate(reply{job=\"helix_logs\"}[5m]))  "
    }
   ]
  },
  {
   "title": "Reply",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "targets": [
    { "expr": "reply" }
   ]
  },
  {
   "title": "Requested Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (filename)(rate(rqst{job=\"helix_logs\"}[5m]))  "
    }
   ]
  },
  {
   "title": "Requested",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 27 },
   "targets": [
    { "expr": "rqst" }
   ]
  },
  {
   "title": "Broadcasted Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (filename)(rate(brdcst{job=\"helix_logs\"}[5m]))  "
    }
   ]
  },
  {
   "title": "Broadcasted",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 36 },
   "targets": [
    { "expr": "brdcst" }
   ]
  }
 ]
}